config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'users#new'
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users, only:[:index, :edit, :update, :new, :create, :show, :destroy]
    resources :labels
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length:{maximum: 30 }
  validates:email,presence:true,length:{maximum: 255 }, format: { with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6 }
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  before_destroy :must_not_destroy_last_admin
  private
  def must_not_destroy_last_admin
    throw(:abort) if User.where(admin: true).count <= 1 && self.admin == true
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :if_not_admin
before_action :set_user, only: [:show, :edit, :update,:destroy]
  def index
    @users = User.select(:id, :name, :email,
    :admin).order(created_at: :asc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  if @user.save
    flash[:success] = "new user added"
    redirect_to admin_users_path(@user.id)
  else
    flash.now[:danger] = "User registration failed"
    render :new
  end
  end

  def show
    @tasks = Task.where(user_id:
      @user.id).page(params[:page]).per(5)
  end

  def edit
  end

  def update
    puts @user
    if @user.update(user_params)
      flash[:success] = "update successful"
      redirect_to admin_user_path(@user)
  else
      flash.now[:danger] = "update failed"
      render :edit
  end
  end

  def destroy
    user = User.find(params[:id])
    if (current_user == user) && (current_user.admin?)
    flash[:error] = "You cannot delete own admin account!"
    redirect_to admin_users_path
    elsif @user.destroy
    flash[:success] = "user deleted!"
    redirect_to admin_users_path
    else
    flash[:danger] = "user not deleted!"
    redirect_to admin_users_path
  end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def if_not_admin
    redirect_to tasks_path(current_user.id) unless current_user.admin?
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :title)
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_owner, except: [:new, :create]
  before_action :authenticate_user, only: [:show]

  def new
    @user = User.new
    if logged_in?
    flash[:alert] = "Already Logged In!"
    redirect_to tasks_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user.id
    flash[:success] = 'User was successfully created'
    redirect_to user_path(@user.id)
    else
    render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    respond_to do |format|
    if @user.update(user_params)
    format.html { redirect_to @user, notice: 'Profile successfully updated.' }
    format.json { render :show, status: :ok, location: @user }
    else
    format.html { render :edit }
    format.json { render json: @user.errors, status: :unprocessable_entity }
    end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_owner
    if current_user != @user && !current_user.admin?
    flash[:alert] = "You can only manage your own account"
    redirect_to tasks_path(@user.id)
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
  <%= form_with(model:[:admin,@user], local:true) do |f| %>
  <div class="form-group">
  <%= f.text_field :name, placeholder: 'name', class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.email_field :email, placeholder: 'email', class: "form control" %>
  </div>
  <div class="form-group">
  <%= f.password_field :password, placeholder: 'password', class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.password_field :password_confirmation, placeholder:'password_confirmation', class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :admin %>
    <%= f.check_box :admin, {}, 'true', 'false' %>  
  </div>  <%= f.submit %>
  <% end %>

app/views/admin/users/edit.html.erb
<h1 class ="center">edit user</h1>
<%= render 'form', user: @user %>
<%= link_to 'return', admin_users_path %>

app/views/admin/users/index.html.erb
<h1 class = "center">List of Users</h1>
<br>
<%= link_to 'Create user', new_admin_user_path, class: "btn btn-info" %>
<hr>
<table class ="table table-striped">
<thead>
<tr>
<th>UserID</th>
<th>Username</th>
<th>Email</th>
<th>User admin priviledges </th>
<th>Number of Tasks</th>
<th></th>
<th colspan="4"></th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
<td><%= user.id %></td>
<td><%= link_to user.name, admin_user_path(user.id) %></td>
<td><%= user.email %></td>
<td><%= user.admin? ? "Yes":"No" %></td>
<td><%= user.tasks.count %></td>
<td><%= link_to 'Show', admin_user_path(user.id), class: "btn btn-outline primary"
%></td>
<td><%= link_to 'Edit', edit_admin_user_path(user.id), data: { confirm:'Are you sure?' }, class: "btn btn-outline-success" %></td>
<td><%= button_to 'Delete', admin_user_path(user.id), data: { confirm:'Are you sure?' }, :method=>:delete, :class=>:destroy %>
</tr>
<% end %>
</tbody>
</table>

app/views/admin/users/new.html.erb
<h1 class ="center">Register</h1>
<%= render 'form', user: @user %>
<%= link_to 'return', admin_users_path %>

app/views/admin/users/show.html.erb
<h1 class = "center"><%=@user.name %>'s page</h1>
<div class ="col-md-6">
<table class="user_show_table clearfix">
<thead>
<tr>
<th>ID</th>
<td><%= @user.id %></td>
</tr>
<tr>
<th>Username</th>
<td><%= @user.name%></td>
</tr>
<tr>
<th>Email</th>
<td><%= @user.email %></td>
</tr>
<tr>
<th>Number of tasks</th>
<td><%= @user.tasks.count %></td>
</tr>
<tr>
<th>User admin priviledges</th>
<td><%= @user.admin? ? "Yes":"No" %></td>
</tr>
<tr>
<th> <%= link_to 'Return', admin_users_path %></th>
</tr>
</thead>
</table>
</div>
<hr>
<div class ="text-right">
<table class="table table-striped">
<thead>
<tr>
<th>Task Name</th>
<th>Task Detail</th>
<th>Expiration date</th>
<th>Status</th>
<th>Priority</th>
</tr>
</thead>
<tbody>
<% @tasks.each do |task| %>
<tr>
<td><%= task.task_name %></td>
<td><%= task.task_detail %></td>
<td><%= task.expiration_date %></td>
<td><%= task.status %></td>
<td><%= task.priority %></td>
</tr>
<% end %>
</tbody>
</table>
</div>